name: Daily Market Summary
on:
  schedule:
    # Run at 8:40 AM IST - adjust timezone as needed
    # This is in cron syntax: minute hour day month day-of-week
    - cron: '10 3 * * *'  # 3:10 AM UTC = 8:40 AM IST
  
  # Allow manual triggering for testing
  workflow_dispatch:

jobs:
  generate-market-summary:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance pandas colorama requests
      
      - name: Run market summary script
        run: python financial_data_fixed.py
        
      - name: Send Slack message
        run: python slack_market_summary.py
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
